services:
  - type: web
    name: aion-server
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./aion-server/Dockerfile
    dockerContext: ./aion-server
    healthCheckPath: /health
    autoDeploy: true
